### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by bfontaine** [chrisbramm/LastFM-History-Graph#2]
Hello there,
Would you mind adding build instructions in the README or another file? How can I compile and use your project? There’s a `.project` file but that’s for Eclipse.

Thanks in advance.

**Comment by chrisbramm** [comment]
I'm on holiday at the moment so it'll be a few weeks but I'll try and remember when I get back?

**Comment by bfontaine** [comment]
Ping? :smile:
